#[derive(Clone)]
pub enum Input {
    Script(&'static str),
    NonFiniteHost,
    NativeReturn,
    NativeInvalidReturn,
    SignatureValid,
    SignatureInvalid,
    AsyncSuccess,
    AsyncExpired,
    ImportSuccess,
    ImportCycle,
    VariablesSuccess,
    VariablesInvalid,
    EmbeddedSuccess,
    EmbeddedLimit,
    RuntimeBoundary,
    AstBoundary,
    AstLimit,
    ImportBudgetBoundary,
    ImportBudgetLimit,
    ValueBoundary,
    ValueLimit,
    ConstructionBoundary,
    ConstructionLimit,
    JsonBudgetBoundary,
    JsonBudgetLimit,
    RetentionBoundary,
    RetentionLimit,
    DefinitionBoundary,
    DefinitionLimit,
    NameBoundary,
    NameLimit,
    RegistryBoundary,
    RegistryLimit,
    SnapshotBoundary,
    SnapshotLimit,
    ResultBoundary,
    ResultLimit,
    TemporaryBoundary,
    TemporaryLimit,
    DiagnosticValueBoundary,
    DiagnosticValueLimit,
    DiagnosticOwnershipBoundary,
    DiagnosticOwnershipLimit,
    DiagnosticAdmissionBoundary,
    DiagnosticAdmissionLimit,
    RuntimeDiagnosticBoundary,
    RuntimeDiagnosticLimit,
    RetainedDiagnosticBoundary,
    RetainedDiagnosticLimit,
    OperationDiagnosticBoundary,
    OperationDiagnosticLimit,
    BorrowedDiagnosticBoundary,
    BorrowedDiagnosticLimit,
    OperationPanicBoundary,
    OperationPanicLimit,
    SignatureDiagnosticBoundary,
    SignatureDiagnosticLimit,
    AccessDiagnosticBoundary,
    AccessDiagnosticLimit,
    OperatorDiagnosticBoundary,
    OperatorDiagnosticLimit,
    HostInputDiagnosticBoundary,
    HostInputDiagnosticLimit,
    HostInputOriginBoundary,
    HostInputOriginLimit,
    SignatureBuilderBoundary,
    SignatureBuilderLimit,
    EntryFileDiagnosticBoundary,
    EntryFileDiagnosticLimit,
    ImportDiagnosticBoundary,
    ImportDiagnosticLimit,
    SetupDiagnosticDefaults,
    SetupDiagnosticLimit,
    CollisionDiagnosticBoundary,
    CollisionDiagnosticLimit,
    ValidationDiagnosticBoundary,
    ValidationDiagnosticLimit,
    SyntaxDiagnosticBoundary,
    SyntaxDiagnosticLimit,
    GuardDiagnosticBoundary,
    GuardDiagnosticLimit,
    WorkerJoinBoundary,
    WorkerJoinLimit,
}

#[derive(Clone)]
pub struct Case {
    pub id: &'static str,
    pub positive: &'static [&'static str],
    pub invalid: &'static [&'static str],
    pub boundary: &'static [&'static str],
    pub input: Input,
    pub stdout: &'static str,
    pub error: Option<&'static str>,
    pub code: Option<&'static str>,
}

fn success(
    id: &'static str,
    source: &'static str,
    stdout: &'static str,
    positive: &'static [&'static str],
    boundary: &'static [&'static str],
) -> Case {
    Case {
        id,
        positive,
        invalid: &[],
        boundary,
        input: Input::Script(source),
        stdout,
        error: None,
        code: None,
    }
}

fn failure(
    id: &'static str,
    source: &'static str,
    stdout: &'static str,
    code: &'static str,
    error: &'static str,
    invalid: &'static [&'static str],
) -> Case {
    Case {
        id,
        positive: &[],
        invalid,
        boundary: &[],
        input: Input::Script(source),
        stdout,
        error: Some(error),
        code: Some(code),
    }
}

pub fn cases() -> Vec<Case> {
    vec![
        success("values", include_str!("values.botwork"), concat!(
            "[none, true, -1, 1.5, \"é\", [], {}]\n[1, 2]\n{\"a\": 2, \"z\": 3}\nfalse\n",
            "[none, none, [\"ok\"]]\n"), &["E2", "V1", "V7", "C2"], &["V7", "C2"]),
        success("control", include_str!("control.botwork"), "[7, 4, 2]\niterator absent\n[false, true]\n",
            &["E1", "E4", "S3", "C1", "F1"], &["S3", "C1"]),
        success("scope", include_str!("scope.botwork"), "[10, 100, [1, 100]]\n10\n11\n11\nlocal discarded\n7\n",
            &["E3", "S1", "S2"], &["E3", "S1", "S2"]),
        success("numeric", include_str!("numeric.botwork"), concat!(
            "[-2147483648, 2147483647, 512, -4, 4, 0.25]\n[true, false, true]\n",
            "[true, true]\nliteral range\narithmetic overflow\n"), &["V2", "V5"], &["V1", "V2", "V5"]),
        success("collections", include_str!("collections.botwork"), concat!(
            "[3, 7, 8, 9, 6]\n[true, true, true, true, false]\n[true, true, false]\n",
            "end is out of bounds\nempty is out of bounds\n"), &["V3", "V4", "V6"], &["V3", "V4", "V6"]),
        success("names", include_str!("names.botwork"), "தமிழ்\ncollision preserves original\n7\n[1, 2, 3, 4]\n8\n",
            &["L3", "L4"], &["L3", "L4"]),
        success("layout", include_str!("../../examples/14-multiline-layout.botwork"), "[2, 3]\né🙂 | # { }\n5\nrecovered\n",
            &["L1", "L2"], &[]),
        success("empty", "", "", &[], &["L1", "C2"]),
        success("call-composition", include_str!("../../examples/18-call-composition.botwork"), "13\n3\nfalse\n120\nfirst\nsecond\n[1, 2]\nBW2001\n", &["E5"], &["E5"]),
        failure("invalid-call-composition", include_str!("../fixtures/invalid-call-composition.botwork"), "", "BW1001", "Parsing error:", &["E5"]),
        failure("call-composition-error", include_str!("../fixtures/call-composition-error.botwork"), "completed first\n", "BW2001", "Variable not defined: missing", &["E3", "E5"]),
        success("crlf-comments", "\t# line\r\n### block\r\ncomment ###\r\n\r\nLog |\"# | { }\"|\r\n", "# | { }\n", &[], &["L1", "L2"]),
        success("recovery", include_str!("recovery.botwork"),
            "before\ncompleted effect\n7\nouter handler\nnot hoisted\nregistered later\n[false, true]\n",
            &["F2", "F3"], &["E1", "E2", "E4", "F1", "F2"]),
        failure("incomplete-continuation", include_str!("../fixtures/invalid-continuation.botwork"), "", "BW1001", "Parsing error:", &["E1", "L1"]),
        failure("unclosed-comment", include_str!("../fixtures/unclosed-block-comment.botwork"), "", "BW1001", "Parsing error:", &["L2"]),
        failure("resolve-before-arguments", "Unknown |missing_argument|", "", "BW2002", "Statement not defined: Unknown", &["E3", "S1"]),
        failure("return-operand-order", "Fail { Return |missing_first + missing_second| }\nLog |\"before\"|\nFail\nLog |\"unreachable\"|", "before\n", "BW2001", "Variable not defined: missing_first", &["E2", "V1", "C2", "F2"]),
        failure("strict-condition", "If |1| { Log |\"unreachable\"| }", "", "BW3003", "If requires a boolean condition", &["E4"]),
        failure("comparison-chain", "Log |1 < 2 < 3|", "", "BW3003", "Operation performed on incompatible types:", &["V2", "V5"]),
        failure("missing-path-key", "Log |{a: 1}.missing|", "", "BW3004", "map key does not exist", &["V3"]),
        failure("computed-key-type", "Log |{a: 1}[0]|", "", "BW3004", "map key must be a string", &["V4"]),
        failure("unsupported-operator", "Log |[1] - [1]|", "", "BW3003", "Operation performed on incompatible types:", &["V7"]),
        failure("duplicate-parameter", include_str!("../fixtures/duplicate-parameter.botwork"), "", "BW1003", "Duplicate parameter `x`", &["L3"]),
        failure("invalid-unicode", include_str!("../fixtures/invalid-unicode-identifier.botwork"), "", "BW1001", "Parsing error:", &["L4"]),
        failure("private-caller", "Read { Return |private| }\nOuter { |private| = |7|\nRead\n}\nOuter", "", "BW2001", "Variable not defined: private", &["S1"]),
        failure("expired-definition", "Outer { Local {} }\nOuter\nLocal", "", "BW2002", "Statement not defined: Local", &["S2"]),
        failure("non-array-iteration", "For |item| In |{}| { Log |\"unreachable\"| }", "", "BW3003", "For requires an array", &["S3"]),
        failure("invalid-control", include_str!("../fixtures/invalid-control-unused-break.botwork"), "", "BW1002", "Break requires", &["C1"]),
        failure("required-catch", include_str!("../fixtures/missing-catch.botwork"), "", "BW1001", "Parsing error:", &["F1"]),
        failure("diagnostic-stack", include_str!("../fixtures/diagnostic-stack.botwork"), "", "BW2001", "diagnostic-stack.botwork:2:17", &["F3"]),
        Case { boundary: &["F3"], ..failure("diagnostic-handler", include_str!("../fixtures/diagnostic-handler.botwork"), "", "BW2001", "while handling:", &["F3"]) },
        success("catch-inspection", include_str!("../../examples/17-catch-details.botwork"), "BW2001\nmissing\noutside\nrethrowing\n[\"BW3002\", true]\noutside\nBW2001\n", &["F4"], &[]),
        failure("rethrow-outside", include_str!("../fixtures/rethrow-outside-catch.botwork"), "", "BW1002", "Rethrow requires", &["F4"]),
        Case { boundary: &["F4"], ..failure("rethrow-original", include_str!("../fixtures/rethrow-original.botwork"), "BW3002\n", "BW3002", "rethrow:", &["F4"]) },
        Case { id: "structural-host-invalid", positive: &[], invalid: &["V6"], boundary: &[],
            input: Input::NonFiniteHost, stdout: "", code: Some("BW3002"), error: Some("Non-finite floating-point operand") },
        Case { id: "native-return", positive: &["F5"], invalid: &[], boundary: &["F5"],
            input: Input::NativeReturn, stdout: "", code: None, error: None },
        Case { id: "native-invalid-return", positive: &[], invalid: &["F5"], boundary: &[],
            input: Input::NativeInvalidReturn, stdout: "", code: Some("BW3002"), error: Some("Non-finite floating-point operand") },
        Case { id: "signature-valid", positive: &["F6"], invalid: &[], boundary: &["F6"],
            input: Input::SignatureValid, stdout: "", code: None, error: None },
        Case { id: "signature-invalid", positive: &[], invalid: &["F6"], boundary: &[],
            input: Input::SignatureInvalid, stdout: "", code: Some("BW3003"), error: Some("Parameter `value` (argument 1)") },
        Case { id: "async-success", positive: &["F7"], invalid: &[], boundary: &["F7"],
            input: Input::AsyncSuccess, stdout: "", code: None, error: None },
        Case { id: "async-expired", positive: &[], invalid: &["F7"], boundary: &[],
            input: Input::AsyncExpired, stdout: "", code: Some("BW5002"), error: Some("Operation deadline expired") },
        Case { id: "import-success", positive: &["M1"], invalid: &[], boundary: &["M1"],
            input: Input::ImportSuccess, stdout: "14\n[1, 2]\nBW6003\n10\n", code: None, error: None },
        Case { id: "import-cycle", positive: &[], invalid: &["M1"], boundary: &[],
            input: Input::ImportCycle, stdout: "", code: Some("BW6002"), error: Some("Import cycle:") },
        Case { id: "variables-success", positive: &["I1"], invalid: &[], boundary: &["I1"],
            input: Input::VariablesSuccess, stdout: "[2, -2147483648, 2147483647, none, true]\n", code: None, error: None },
        Case { id: "variables-invalid", positive: &[], invalid: &["I1"], boundary: &[],
            input: Input::VariablesInvalid, stdout: "", code: Some("BW7001"), error: Some("integer is outside") },
        Case { id: "embedded-success", positive: &["R1"], invalid: &[], boundary: &["R1"],
            input: Input::EmbeddedSuccess, stdout: "", code: None, error: None },
        Case { id: "embedded-limit", positive: &[], invalid: &["R1"], boundary: &[],
            input: Input::EmbeddedLimit, stdout: "", code: Some("BW8001"), error: Some("evaluation steps") },
        success("syntax-boundary", include_str!("syntax-boundary.botwork"), "65\n1\n", &["R2"], &["R2"]),
        failure("syntax-limit", include_str!("syntax-limit.botwork"), "", "BW8001", "expression operators", &["R2"]),
        Case { id: "runtime-boundary", positive: &["R3"], invalid: &[], boundary: &["R3"],
            input: Input::RuntimeBoundary, stdout: "", code: None, error: None },
        failure("runtime-recursion", include_str!("runtime-recursion.botwork"), "", "BW8001", "call depth", &["R3"]),
        Case { id: "ast-boundary", positive: &["R4"], invalid: &[], boundary: &["R4"],
            input: Input::AstBoundary, stdout: "", code: None, error: None },
        Case { id: "ast-limit", positive: &[], invalid: &["R4"], boundary: &[],
            input: Input::AstLimit, stdout: "", code: Some("BW8001"), error: Some("AST nodes") },
        Case { id: "import-budget-boundary", positive: &["R5"], invalid: &[], boundary: &["R5"],
            input: Input::ImportBudgetBoundary, stdout: "", code: None, error: None },
        Case { id: "import-budget-limit", positive: &[], invalid: &["R5"], boundary: &[],
            input: Input::ImportBudgetLimit, stdout: "", code: Some("BW8001"), error: Some("imported bindings") },
        Case { id: "value-boundary", positive: &["R6"], invalid: &[], boundary: &["R6"],
            input: Input::ValueBoundary, stdout: "", code: None, error: None },
        Case { id: "value-limit", positive: &[], invalid: &["R6"], boundary: &[],
            input: Input::ValueLimit, stdout: "", code: Some("BW8001"), error: Some("value container entries") },
        Case { id: "construction-boundary", positive: &["R7"], invalid: &[], boundary: &["R7"],
            input: Input::ConstructionBoundary, stdout: "", code: None, error: None },
        Case { id: "construction-limit", positive: &[], invalid: &["R7"], boundary: &[],
            input: Input::ConstructionLimit, stdout: "", code: Some("BW8001"), error: Some("value container entries") },
        Case { id: "input-budget-boundary", positive: &["R8"], invalid: &[], boundary: &["R8"],
            input: Input::JsonBudgetBoundary, stdout: "", code: None, error: None },
        Case { id: "input-budget-limit", positive: &[], invalid: &["R8"], boundary: &[],
            input: Input::JsonBudgetLimit, stdout: "", code: Some("BW8001"), error: Some("input raw nodes") },
        Case { id: "retention-boundary", positive: &["R9"], invalid: &[], boundary: &["R9"],
            input: Input::RetentionBoundary, stdout: "", code: None, error: None },
        Case { id: "retention-limit", positive: &[], invalid: &["R9"], boundary: &[],
            input: Input::RetentionLimit, stdout: "", code: Some("BW8001"), error: Some("retained values") },
        Case { id: "definition-boundary", positive: &["R10"], invalid: &[], boundary: &["R10"],
            input: Input::DefinitionBoundary, stdout: "", code: None, error: None },
        Case { id: "definition-limit", positive: &[], invalid: &["R10"], boundary: &[],
            input: Input::DefinitionLimit, stdout: "", code: Some("BW8001"), error: Some("retained definitions") },
        Case { id: "name-boundary", positive: &["R11"], invalid: &[], boundary: &["R11"],
            input: Input::NameBoundary, stdout: "", code: None, error: None },
        Case { id: "name-limit", positive: &[], invalid: &["R11"], boundary: &[],
            input: Input::NameLimit, stdout: "", code: Some("BW8001"), error: Some("retained variable name bytes") },
        Case { id: "registry-boundary", positive: &["R12"], invalid: &[], boundary: &["R12"],
            input: Input::RegistryBoundary, stdout: "", code: None, error: None },
        Case { id: "registry-limit", positive: &[], invalid: &["R12"], boundary: &[],
            input: Input::RegistryLimit, stdout: "", code: Some("BW8001"), error: Some("registry text bytes") },
        Case { id: "snapshot-boundary", positive: &["R13"], invalid: &[], boundary: &["R13"],
            input: Input::SnapshotBoundary, stdout: "", code: None, error: None },
        Case { id: "snapshot-limit", positive: &[], invalid: &["R13"], boundary: &[],
            input: Input::SnapshotLimit, stdout: "", code: Some("BW8001"), error: Some("snapshot table entries") },
        Case { id: "result-boundary", positive: &["R14"], invalid: &[], boundary: &["R14"],
            input: Input::ResultBoundary, stdout: "", code: None, error: None },
        Case { id: "result-limit", positive: &[], invalid: &["R14"], boundary: &[],
            input: Input::ResultLimit, stdout: "", code: Some("BW8001"), error: Some("result payload bytes") },
        Case { id: "temporary-boundary", positive: &["R15"], invalid: &[], boundary: &["R15"],
            input: Input::TemporaryBoundary, stdout: "", code: None, error: None },
        Case { id: "temporary-limit", positive: &[], invalid: &["R15"], boundary: &[],
            input: Input::TemporaryLimit, stdout: "", code: Some("BW8001"), error: Some("temporary value payload bytes") },
        Case { id: "diagnostic-value-boundary", positive: &["R16"], invalid: &[], boundary: &["R16"],
            input: Input::DiagnosticValueBoundary, stdout: "", code: None, error: None },
        Case { id: "diagnostic-value-limit", positive: &[], invalid: &["R16"], boundary: &[],
            input: Input::DiagnosticValueLimit, stdout: "", code: Some("BW8001"), error: Some("value nodes") },
        Case { id: "diagnostic-ownership-boundary", positive: &["R17"], invalid: &[], boundary: &["R17"],
            input: Input::DiagnosticOwnershipBoundary, stdout: "", code: None, error: None },
        Case { id: "diagnostic-ownership-limit", positive: &[], invalid: &["R17"], boundary: &[],
            input: Input::DiagnosticOwnershipLimit, stdout: "", code: Some("BW8001"), error: Some("diagnostic text bytes") },
        Case { id: "diagnostic-admission-boundary", positive: &["R17"], invalid: &[], boundary: &["R17"],
            input: Input::DiagnosticAdmissionBoundary, stdout: "", code: None, error: None },
        Case { id: "diagnostic-admission-limit", positive: &[], invalid: &["R17"], boundary: &[],
            input: Input::DiagnosticAdmissionLimit, stdout: "", code: Some("BW8001"), error: Some("diagnostic text bytes") },
        Case { id: "runtime-diagnostic-boundary", positive: &["R18"], invalid: &[], boundary: &["R18"],
            input: Input::RuntimeDiagnosticBoundary, stdout: "", code: None, error: None },
        Case { id: "runtime-diagnostic-limit", positive: &[], invalid: &["R18"], boundary: &[],
            input: Input::RuntimeDiagnosticLimit, stdout: "", code: Some("BW8001"), error: Some("diagnostic nodes") },
        Case { id: "retained-diagnostic-boundary", positive: &["R19"], invalid: &[], boundary: &["R19"],
            input: Input::RetainedDiagnosticBoundary, stdout: "", code: None, error: None },
        Case { id: "retained-diagnostic-limit", positive: &[], invalid: &["R19"], boundary: &[],
            input: Input::RetainedDiagnosticLimit, stdout: "", code: Some("BW8001"), error: Some("retained diagnostic records") },
        Case { id: "operation-diagnostic-boundary", positive: &["R20"], invalid: &[], boundary: &["R20"],
            input: Input::OperationDiagnosticBoundary, stdout: "", code: None, error: None },
        Case { id: "operation-diagnostic-limit", positive: &[], invalid: &["R20"], boundary: &[],
            input: Input::OperationDiagnosticLimit, stdout: "", code: Some("BW8001"), error: Some("diagnostic text bytes") },
        Case { id: "borrowed-diagnostic-boundary", positive: &["R21"], invalid: &[], boundary: &["R21"],
            input: Input::BorrowedDiagnosticBoundary, stdout: "", code: None, error: None },
        Case { id: "borrowed-diagnostic-limit", positive: &[], invalid: &["R21"], boundary: &[],
            input: Input::BorrowedDiagnosticLimit, stdout: "", code: Some("BW8001"), error: Some("diagnostic text bytes") },
        Case { id: "operation-panic-boundary", positive: &["R21"], invalid: &[], boundary: &["R21"],
            input: Input::OperationPanicBoundary, stdout: "", code: None, error: None },
        Case { id: "operation-panic-limit", positive: &[], invalid: &["R21"], boundary: &[],
            input: Input::OperationPanicLimit, stdout: "", code: Some("BW8001"), error: Some("diagnostic text bytes") },
        Case { id: "signature-diagnostic-boundary", positive: &["R21"], invalid: &[], boundary: &["R21"],
            input: Input::SignatureDiagnosticBoundary, stdout: "", code: None, error: None },
        Case { id: "signature-diagnostic-limit", positive: &[], invalid: &["R21"], boundary: &[],
            input: Input::SignatureDiagnosticLimit, stdout: "", code: Some("BW8001"), error: Some("diagnostic text bytes") },
        Case { id: "access-diagnostic-boundary", positive: &["R21"], invalid: &[], boundary: &["R21"],
            input: Input::AccessDiagnosticBoundary, stdout: "", code: None, error: None },
        Case { id: "access-diagnostic-limit", positive: &[], invalid: &["R21"], boundary: &[],
            input: Input::AccessDiagnosticLimit, stdout: "", code: Some("BW8001"), error: Some("diagnostic text bytes") },
        Case { id: "operator-diagnostic-boundary", positive: &["R21"], invalid: &[], boundary: &["R21"],
            input: Input::OperatorDiagnosticBoundary, stdout: "", code: None, error: None },
        Case { id: "operator-diagnostic-limit", positive: &[], invalid: &["R21"], boundary: &[],
            input: Input::OperatorDiagnosticLimit, stdout: "", code: Some("BW8001"), error: Some("diagnostic text bytes") },
        Case { id: "input-diagnostic-boundary", positive: &["R21"], invalid: &[], boundary: &["R21"],
            input: Input::HostInputDiagnosticBoundary, stdout: "", code: None, error: None },
        Case { id: "input-diagnostic-limit", positive: &[], invalid: &["R21"], boundary: &[],
            input: Input::HostInputDiagnosticLimit, stdout: "", code: Some("BW8001"), error: Some("diagnostic text bytes") },
        Case { id: "input-origin-boundary", positive: &["R21"], invalid: &[], boundary: &["R21"],
            input: Input::HostInputOriginBoundary, stdout: "", code: None, error: None },
        Case { id: "input-origin-limit", positive: &[], invalid: &["R21"], boundary: &[],
            input: Input::HostInputOriginLimit, stdout: "", code: Some("BW8001"), error: Some("diagnostic source bytes") },
        Case { id: "signature-builder-boundary", positive: &["R21"], invalid: &[], boundary: &["R21"],
            input: Input::SignatureBuilderBoundary, stdout: "", code: None, error: None },
        Case { id: "signature-builder-limit", positive: &[], invalid: &["R21"], boundary: &[],
            input: Input::SignatureBuilderLimit, stdout: "", code: Some("BW8001"), error: Some("diagnostic text bytes") },
        Case { id: "entry-file-diagnostic-boundary", positive: &["R21"], invalid: &[], boundary: &["R21"],
            input: Input::EntryFileDiagnosticBoundary, stdout: "", code: None, error: None },
        Case { id: "entry-file-diagnostic-limit", positive: &[], invalid: &["R21"], boundary: &[],
            input: Input::EntryFileDiagnosticLimit, stdout: "", code: Some("BW8001"), error: Some("diagnostic text bytes") },
        Case { id: "import-diagnostic-boundary", positive: &["R21"], invalid: &[], boundary: &["R21"],
            input: Input::ImportDiagnosticBoundary, stdout: "", code: None, error: None },
        Case { id: "import-diagnostic-limit", positive: &[], invalid: &["R21"], boundary: &[],
            input: Input::ImportDiagnosticLimit, stdout: "", code: Some("BW8001"), error: Some("diagnostic text bytes") },
        Case { id: "setup-diagnostic-defaults", positive: &["R21"], invalid: &[], boundary: &["R21"],
            input: Input::SetupDiagnosticDefaults, stdout: "", code: None, error: None },
        Case { id: "setup-diagnostic-limit", positive: &[], invalid: &["R21"], boundary: &[],
            input: Input::SetupDiagnosticLimit, stdout: "", code: Some("BW8001"), error: Some("diagnostic text bytes") },
        Case { id: "collision-diagnostic-boundary", positive: &["R21"], invalid: &[], boundary: &["R21"],
            input: Input::CollisionDiagnosticBoundary, stdout: "", code: None, error: None },
        Case { id: "collision-diagnostic-limit", positive: &[], invalid: &["R21"], boundary: &[],
            input: Input::CollisionDiagnosticLimit, stdout: "", code: Some("BW8001"), error: Some("diagnostic text bytes") },
        Case { id: "validation-diagnostic-boundary", positive: &["R21"], invalid: &[], boundary: &["R21"],
            input: Input::ValidationDiagnosticBoundary, stdout: "", code: None, error: None },
        Case { id: "validation-diagnostic-limit", positive: &[], invalid: &["R21"], boundary: &[],
            input: Input::ValidationDiagnosticLimit, stdout: "", code: Some("BW8001"), error: Some("diagnostic text bytes") },
        Case { id: "syntax-diagnostic-boundary", positive: &["R21"], invalid: &[], boundary: &["R21"],
            input: Input::SyntaxDiagnosticBoundary, stdout: "", code: None, error: None },
        Case { id: "syntax-diagnostic-limit", positive: &[], invalid: &["R21"], boundary: &[],
            input: Input::SyntaxDiagnosticLimit, stdout: "", code: Some("BW8001"), error: Some("diagnostic text bytes") },
        Case { id: "guard-diagnostic-boundary", positive: &["R21"], invalid: &[], boundary: &["R21"],
            input: Input::GuardDiagnosticBoundary, stdout: "", code: None, error: None },
        Case { id: "guard-diagnostic-limit", positive: &[], invalid: &["R21"], boundary: &[],
            input: Input::GuardDiagnosticLimit, stdout: "", code: Some("BW8001"), error: Some("diagnostic source bytes") },
        Case { id: "worker-join-boundary", positive: &["R21"], invalid: &[], boundary: &["R21"],
            input: Input::WorkerJoinBoundary, stdout: "", code: None, error: None },
        Case { id: "worker-join-limit", positive: &[], invalid: &["R21"], boundary: &[],
            input: Input::WorkerJoinLimit, stdout: "", code: Some("BW8001"), error: Some("diagnostic source bytes") },
    ]
}
