// Static resource names for protocol v1. Hosts may explicitly register extras.
pub(super) const RESOURCES: &[&str] = &[
    "AST depth",
    "AST nodes",
    "AST source bytes",
    "call depth",
    "combined syntax complexity",
    "diagnostic call frames",
    "diagnostic depth",
    "diagnostic nodes",
    "diagnostic position bytes",
    "diagnostic related locations",
    "diagnostic render call frames",
    "diagnostic render depth",
    "diagnostic render output bytes",
    "diagnostic render records",
    "diagnostic render related locations",
    "diagnostic render source scan bytes",
    "diagnostic source bytes",
    "diagnostic text bytes",
    "evaluation depth",
    "evaluation steps",
    "expression operators",
    "import initialization depth",
    "import metadata bytes",
    "imported bindings",
    "input raw nodes",
    "input source bytes",
    "input sources",
    "input variables",
    "isolated workers",
    "module dependency depth",
    "module load attempts",
    "module path cache entries",
    "module source bytes",
    "operation diagnostic call frames",
    "operation diagnostic nodes",
    "operation diagnostic related locations",
    "operation diagnostic source bytes",
    "operation diagnostic text bytes",
    "operation invocations",
    "operation value nodes",
    "operation value payload bytes",
    "operation values",
    "output record bytes",
    "output total bytes",
    "parser caller depth",
    "registry entries",
    "registry name bytes",
    "registry nodes",
    "registry source bytes",
    "registry text bytes",
    "result name bytes",
    "result nodes",
    "result payload bytes",
    "result values",
    "retained definition nodes",
    "retained definition source bytes",
    "retained definitions",
    "retained diagnostic call frames",
    "retained diagnostic nodes",
    "retained diagnostic records",
    "retained diagnostic related locations",
    "retained diagnostic source bytes",
    "retained diagnostic text bytes",
    "retained value nodes",
    "retained value payload bytes",
    "retained values",
    "retained variable name bytes",
    "retained variable names",
    "snapshot path bytes",
    "snapshot table entries",
    "source bytes",
    "stack headroom bytes",
    "syntax nesting",
    "temporary value nodes",
    "temporary value payload bytes",
    "temporary values",
    "total input bytes",
    "value container entries",
    "value depth",
    "value key bytes",
    "value nodes",
    "value payload bytes",
    "value string bytes",
    "variable name bytes",
    "worker protocol argument nodes",
    "worker protocol argument payload bytes",
    "worker protocol arguments",
    "worker protocol frame bytes",
    "worker protocol in-flight bytes",
    "worker protocol sources",
    "worker request bytes",
    "worker stderr bytes",
    "worker stdout bytes",
];
