#![doc = include_str!("../docs/rust-api.md")]
#![doc = include_str!("../docs/interpreter-architecture.md")]
#![doc = include_str!("../docs/async-execution.md")]
#![doc = include_str!("../docs/nonblocking-io.md")]
#![doc = include_str!("../docs/parameterized-cases.md")]
#![doc = include_str!("../docs/cleanup.md")]
#![doc = include_str!("../docs/fixtures.md")]
#![doc = include_str!("../docs/acceptance-policy.md")]
#![doc = include_str!("../docs/run-records.md")]
#![doc = include_str!("../docs/listeners.md")]
#![doc = include_str!("../docs/secrets.md")]
#![doc = include_str!("../docs/shutdown.md")]
#![doc = include_str!("../docs/check.md")]

pub mod core;
